### ISSUE TITLE
Add Attribute Selection to Resource-Types

### ISSUE THREAD

**Issue by ItIsGreg** [ItIsGreg/structurer#3]
In the Labeler Section there need to be a attribute selection.

First focus on core FHIR-Resource types. Attribute options as constants in constant file. Default selection as constants in constants file.

On hover show attributes to be extracted. On right click allow selection of attributes. Use Selection Backbone-Component.

Just implement front-end-side. Handle Back-end later.

Where to store attribute selection? Keep in state for now.

**ToDos:**

- [x] Show selected attributes in tooltip
- [x] Create modal for attribute selection (use CategorySelector)
- [x] Make LLM call to Attribute API endpoint
- [x] Integrate with Outline
- [x] integrate with Unmatch Logic
- [x] show attributes in outline tab on hover

**Considerations**
- make two label buttons for now, one with, one without attributes
- integrate in outline so that attributes remain optional
